spring.datasource.url=jdbc:postgresql://localhost:5432/medileave_db
spring.datasource.username=postgres
spring.datasource.password=4WogrX66

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

app.jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey12345
app.jwt.expiration=86400000
app.upload.dir=uploads/medical-leaves
server.port=8181